from telebot import types

level_1_menu = types.ReplyKeyboardMarkup(resize_keyboard=True)
menu_1 = types.KeyboardButton('1. Станки')
menu_2 = types.KeyboardButton('2. Нечеткое задание (проблемы оформления)')
menu_3 = types.KeyboardButton('3. Склад')
menu_4 = types.KeyboardButton('4. Операторы')
menu_5 = types.KeyboardButton('5. Нет задания – огрехи планирования')
level_1_menu.row(menu_1, menu_2)
level_1_menu.row(menu_3, menu_4, menu_5)

level_2_stanki = types.ReplyKeyboardMarkup(resize_keyboard=True)
stanok_1_1 = types.KeyboardButton('Highflex 1650 FC')
stanok_2_1 = types.KeyboardButton('HPL 300/38/22')
stanok_3_1 = types.KeyboardButton('KTD 720')
stanok_4_1 = types.KeyboardButton('Назад')
level_2_stanki.row(stanok_1_1, stanok_2_1, stanok_3_1, stanok_4_1)

level_3_stanki = types.ReplyKeyboardMarkup(row_width=2)
stanok_1_2 = types.KeyboardButton('a. Компьютер завис')
stanok_2_2 = types.KeyboardButton('b. Клеенаносящий узел')
stanok_3_2 = types.KeyboardButton('c. Подфуговка')
stanok_4_2 = types.KeyboardButton('d. Торцовка')
stanok_5_2 = types.KeyboardButton('e. Радиусная обработка фрезами')
stanok_6_2 = types.KeyboardButton('f. Раунд – фрезы')
stanok_7_2 = types.KeyboardButton('g. Цикли')
stanok_8_2 = types.KeyboardButton('Назад')
level_3_stanki.add(stanok_1_2, stanok_2_2, stanok_3_2, stanok_4_2)
level_3_stanki.add(stanok_5_2, stanok_6_2, stanok_7_2, stanok_8_2)

level_2_zadanie = types.ReplyKeyboardMarkup()
task_1 = types.KeyboardButton('a. Указать номер заказа')
task_2 = types.KeyboardButton('Назад')

level_2_sklad = types.ReplyKeyboardMarkup()
storage_1 = types.KeyboardButton('a. Мало кромки')
storage_2 = types.KeyboardButton('b. Нет кромки вообще к заказу')
storage_3 = types.KeyboardButton('Назад')

level_2_operatori = types.ReplyKeyboardMarkup()
operator_1 = types.KeyboardButton('a. Перекур не по графику')
operator_2 = types.KeyboardButton('b. Кривые руки')
operator_3 = types.KeyboardButton('Назад')
